/**
 * listings.js – static property data for AccoFinder home feed.
 * Consumed by home.js to render and filter cards dynamically.
 */

const LISTINGS = [
  {
    id: 'listing-001',
    name: 'McIntyre Property',
    initial: 'M',
    avatarStyle: '',
    location: 'Braamfontein',
    postedAgo: '2d ago',
    verified: true,
    description: 'Spacious 2-bedroom flat, fully furnished. Walking distance to Wits University. Includes Wi-Fi, water & electricity. Safe and secure with 24/7 access control.',
    price: 'R3 500/mo',
    type: '2-Bedroom',
    distance: '0.8 km to Wits',
    rooms: '4 units left',
    categories: ['all', 'near-campus', 'flats', 'verified'],
    amenities: [
      { icon: 'wifi',      label: 'Wi-Fi' },
      { icon: 'calendar',  label: 'Available Jan' },
      { icon: 'location',  label: 'Braamfontein' },
      { icon: 'lock',      label: 'Secure' },
    ],
    photoEmoji: '🏢',
    photoGradient: 'linear-gradient(135deg,#1877F2,#1D9E75)',
    photoSide1Emoji: '🛏',
    photoSide1Bg: '#C5E8F5',
    photoSide2Emoji: '🛁',
    photoSide2Bg: '#D4F0E0',
    photoExtra: 5,
    interested: 24,
    applications: 18,
    views: 3,
    adminPending: true,
  },
  {
    id: 'listing-002',
    name: 'Sophiatown Residence',
    initial: 'S',
    avatarStyle: 'background:var(--fb-blue-light); color:var(--fb-blue-dark);',
    location: 'Melville',
    postedAgo: '5h ago',
    verified: true,
    description: 'Single room en-suite in a fully managed student residence. Meals included. 24/7 security, laundry on-site. All bills included.',
    price: 'R2 800/mo',
    type: 'Single Room',
    distance: '1.2 km to UJ',
    rooms: 'Bills incl.',
    categories: ['all', 'near-campus', 'rooms', 'verified'],
    amenities: [
      { icon: 'meals',    label: 'Meals Incl.' },
      { icon: 'laundry',  label: 'Laundry' },
      { icon: 'location', label: 'Melville' },
      { icon: 'lock',     label: 'Secure' },
    ],
    photoEmoji: '🏛',
    photoGradient: 'linear-gradient(135deg,#1877F2 20%,#7F77DD 100%)',
    photoSide1Emoji: '🛏',
    photoSide1Bg: '#E8EAF6',
    photoSide2Emoji: '🍽',
    photoSide2Bg: '#E3F2FD',
    photoExtra: 8,
    interested: 11,
    applications: 7,
    views: 0,
    adminPending: false,
  },
  {
    id: 'listing-003',
    name: 'Parktown Heights',
    initial: 'P',
    avatarStyle: 'background:#FFF3E0; color:#BF5000;',
    location: 'Parktown',
    postedAgo: '1d ago',
    verified: true,
    description: 'Modern 3-bedroom house ideal for a group of students. Fully furnished with a garden, high-speed fibre, and off-street parking. Quiet neighbourhood close to Wits Medical School.',
    price: 'R4 200/mo',
    type: '3-Bedroom',
    distance: '0.5 km to Wits',
    rooms: '2 units left',
    categories: ['all', 'near-campus', 'houses', 'verified'],
    amenities: [
      { icon: 'wifi',      label: 'Fibre' },
      { icon: 'parking',   label: 'Parking' },
      { icon: 'location',  label: 'Parktown' },
      { icon: 'lock',      label: 'Secure' },
    ],
    photoEmoji: '🏗',
    photoGradient: 'linear-gradient(135deg,#F5A623,#E8453C)',
    photoSide1Emoji: '🚗',
    photoSide1Bg: '#FFF3E0',
    photoSide2Emoji: '🌿',
    photoSide2Bg: '#E8F5E9',
    photoExtra: 4,
    interested: 33,
    applications: 12,
    views: 8,
    adminPending: false,
  },
  {
    id: 'listing-004',
    name: 'Melville Student House',
    initial: 'M',
    avatarStyle: 'background:#F3E8FF; color:#5B21B6;',
    location: 'Melville',
    postedAgo: '3d ago',
    verified: false,
    description: 'Affordable single rooms in a shared student house. Common kitchen & lounge. Friendly community atmosphere with other students. Close to UJ and Wits campuses.',
    price: 'R1 900/mo',
    type: 'Single Room',
    distance: '2.1 km',
    rooms: 'Shared kitchen',
    categories: ['all', 'rooms'],
    amenities: [
      { icon: 'wifi',     label: 'Wi-Fi' },
      { icon: 'calendar', label: 'Available Now' },
      { icon: 'location', label: 'Melville' },
      { icon: 'meals',    label: 'Shared Kitchen' },
    ],
    photoEmoji: '🏘',
    photoGradient: 'linear-gradient(135deg,#9C27B0,#673AB7)',
    photoSide1Emoji: '🛏',
    photoSide1Bg: '#F3E8FF',
    photoSide2Emoji: '🍳',
    photoSide2Bg: '#E8F5E9',
    photoExtra: 3,
    interested: 8,
    applications: 5,
    views: 2,
    adminPending: true,
  },
  {
    id: 'listing-005',
    name: 'Newtown Flat',
    initial: 'N',
    avatarStyle: 'background:#E8F5E9; color:#1B5E20;',
    location: 'Newtown',
    postedAgo: '12h ago',
    verified: true,
    description: 'Contemporary studio flat in the vibrant Newtown arts district. Perfect for a solo student. Includes all utilities, smart TV, and high-speed internet. Walking distance to transport hubs.',
    price: 'R3 100/mo',
    type: 'Studio Flat',
    distance: '1.8 km',
    rooms: 'All bills incl.',
    categories: ['all', 'flats', 'verified'],
    amenities: [
      { icon: 'wifi',     label: 'Wi-Fi' },
      { icon: 'calendar', label: 'Available Feb' },
      { icon: 'location', label: 'Newtown' },
      { icon: 'lock',     label: 'Secure' },
    ],
    photoEmoji: '🏙',
    photoGradient: 'linear-gradient(135deg,#1D9E75,#1877F2)',
    photoSide1Emoji: '🛁',
    photoSide1Bg: '#E8F5E9',
    photoSide2Emoji: '📺',
    photoSide2Bg: '#E3F2FD',
    photoExtra: 6,
    interested: 19,
    applications: 9,
    views: 5,
    adminPending: false,
  },
];
